# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
  

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print Hello Message in Testing
      run: echo "Hello world from Testing"
      
    - name: Execute few commnads
      run: |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
          
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    steps:
    - name: Print Hello Message in Deploy
      run: echo "Hello world from Deploy"
      
    - name: Printing Deployment Package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
    - name: Lets packages if the are here 1
      run: aws --version
      
    - name: Lets packages if the are here 2
      run: zip
    
